attempt-this-online/languages

- languages/jelly/Dockerfile
First attempt at this =) Shout out if you do not want pull requests, or if I did something horribly wrong.
> Added support for Jelly

- languages/05ab1e/Dockerfile
I've tested this and it works fine. Run with `escript /opt/05ab1e/osabie path/to/file.abe`.
> Add 05AB1E

- languages/05ab1e/Dockerfile
[The build still failed](https://github.com/attempt-this-online/languages/runs/6509174760?check_suite_focus=true) with some other weird error, so hopefully this works...
> Just throw away yes

- languages/charcoal/Dockerfile
- languages/whitespace/Dockerfile
> Add Whitespace and Charcoal

- languages/knight/Dockerfile
I couldn't get c/ast to work. Errors, then segfaults. So I just used the JS implementation.
> Add Knight

- languages/vyxal/Dockerfile
See you next week with another version bump
> Version bump Vyxal to 2.17.0

- languages/vyxal/Dockerfile
Told ya I'd be back with another version bump :p
See you again next week with yet another one of these commits and PRs
> Bump Vyxal to 2.17.1

- languages/curry_pakcs/Dockerfile
- languages/pari_gp/Dockerfile
Curry(PAKCS): 3.3.0 -> 3.5.0
PARI/GP: 2.13.4 -> 2.15.0
> update Curry(PAKCS) and PARI/GP

- languages/chapel/Dockerfile
- languages/clang/Dockerfile
Tested that this builds and `chpl` executes on it.
> Add Dockerfile for Chapel language

- languages/thunno/Dockerfile
Sorry about making another PR so quickly. There was a pretty major bug which I had to fix.
> Bump Thunno to v1.0.2

- languages/thunno/Dockerfile
Sorry for making another PR so soon, but there was a major change (1.0 -> 1.1). Hopefully from now there will be less frequent major changes.
> Bump Thunno to 1.1.0

- languages/thunno/Dockerfile
Another major update (1.1 -> 1.2).
> Bump Thunno to v1.2.1

- languages/thunno2/Dockerfile
Let me know if there's anything else I need to do.
> Add Thunno 2

- languages/minigolf/Dockerfile
> Bump to v0.4

- languages/flip/Dockerfile
Hope it works (I tested it this time).
> Bump Flip to v1.2

- languages/factor/Dockerfile
There's a new vocab that I'd like to use in ATO :P
> Bump Factor to latest release

- languages/backhand/Dockerfile
- languages/labyrinth/Dockerfile
I checked that the interpreters work with the latest versions of Python and Ruby respectively.
> Add Backhand and Labyrinth

- languages/python/Dockerfile
(This is really just to test the new pull request workflow - see 4bc1fb0)
> Update Python to 3.12.2

- .github/workflows/build.yml
> fix GitHub Actions error handling

- languages/chapel/Dockerfile
This is a simple update to reflect the new version of Chapel that's now available.
> Update Chapel to reflect last week's 2.1 release

- languages/chapel/Dockerfile
Thanks for continuing to maintain the ATO website.  It is so incredibly useful!
> Update Chapel to reflect today's 2.4 release

- languages/j_but_longer/Dockerfile
https://github.com/jsoftware/jsource/issues/225#issuecomment-2977530862
> better fix for J
